"""
Behavioral tests for the instance identity fact [ES-020/DEC-026]: every
history this kernel writes opens with ``InstanceCreated`` — the unique
instance id (minted or supplied) and the net definition's optional ``name``
— and resume derives identity from that record, never from a re-supplied
argument. Identity is a fact, not code; nothing semantic reads it.
"""

from __future__ import annotations

# Pip imports
import pytest

# Internal imports
from petrus.impetus.history import InstanceCreated, replay_instance_identity, replay_next_occurrence
from petrus.impetus.history_store import InMemoryHistoryStore
from petrus.impetus.petrinet import Marking, Token
from petrus.impetus.instance import Instance
from petrus.impetus.petrinet import Arc, Net, NetPath, Place, Transition

A, B, T = NetPath("a"), NetPath("b"), NetPath("t")


def _net(name: str | None = None) -> Net:
    return Net(places=[Place(A), Place(B)], transitions=[Transition(T)], arcs=[Arc(A, T), Arc(T, B)], name=name)


class TestNetName:
    def test_the_definition_name_is_optional_and_descriptive(self):
        assert _net().name is None
        assert _net("order-fulfillment").name == "order-fulfillment"

    def test_an_empty_or_non_string_name_is_refused(self):
        with pytest.raises(ValueError, match="net name"):
            _net("")
        with pytest.raises(ValueError, match="net name"):
            _net(7)


class TestIdentityIsRecordedFirst:
    def test_construction_records_the_identity_fact_before_anything(self):
        instance = Instance(_net("order-fulfillment"), Marking({A: (Token("X"),)}), at=5, instance_id="order-7")

        assert instance.history.records[0] == InstanceCreated("order-7", name="order-fulfillment", instant=5)

    def test_an_unsupplied_id_is_minted_unique_and_creation_ordered(self):
        # uuid7 by Navigator ruling (2026-07-17): minted ids sort by mint
        # time, so a fleet's instances order by creation in any index.
        first = Instance(_net())
        second = Instance(_net())

        assert first.instance_id < second.instance_id
        assert first.history.records[0] == InstanceCreated(first.instance_id)

    def test_an_unnamed_net_records_no_name(self):
        instance = Instance(_net(), instance_id="order-7")
        assert instance.history.records[0] == InstanceCreated("order-7", name=None)


class TestResumeDerivesIdentity:
    def test_resume_reads_the_recorded_identity_back(self):
        instance = Instance(_net("order-fulfillment"), Marking({A: (Token("X"),)}), instance_id="order-7")
        instance.run()

        resumed = Instance.resume(_net("order-fulfillment"), instance.history)

        assert resumed.instance_id == "order-7"

    def test_identity_survives_a_crash_that_a_resupplied_argument_would_not(self):
        # The autogenerated id is deterministic under replay because it is a
        # record: a fresh resume needs no argument to keep the same identity.
        instance = Instance(_net(), Marking({A: (Token("X"),)}))
        instance.run()

        assert Instance.resume(_net(), instance.history).instance_id == instance.instance_id

    def test_a_pre_identity_trace_resumes_unidentified(self):
        instance = Instance(_net(), Marking({A: (Token("X"),)}))
        instance.run()
        legacy = InMemoryHistoryStore()
        legacy.extend(list(instance.history.records[1:]))  # a trace older than the identity fact

        assert Instance.resume(_net(), legacy).instance_id is None

    def test_a_recorded_name_disagreeing_with_the_supplied_net_is_a_foreign_trace(self):
        instance = Instance(_net("order-fulfillment"), Marking({A: (Token("X"),)}))
        instance.run()

        with pytest.raises(ValueError, match="foreign trace"):
            Instance.resume(_net("billing"), instance.history)

    def test_an_unnamed_resupplied_net_accepts_a_named_trace(self):
        # Strictness only where both sides claim a name: the caller declining
        # to name the net is not a disagreement.
        instance = Instance(_net("order-fulfillment"), Marking({A: (Token("X"),)}))
        instance.run()

        assert Instance.resume(_net(), instance.history).instance_id == instance.instance_id


class TestIdentityFolds:
    def test_a_mid_trace_identity_fact_is_replay_divergence(self):
        instance = Instance(_net(), Marking({A: (Token("X"),)}))
        instance.run()
        corrupted = InMemoryHistoryStore()
        corrupted.extend([*instance.history.records, InstanceCreated("intruder")])

        with pytest.raises(ValueError, match="replay divergence"):
            replay_instance_identity(corrupted)

    def test_the_identity_fact_is_occurrence_less_by_classification(self):
        # Convention 49: the occurrence fold excludes InstanceCreated
        # deliberately, not by silent getattr.
        history = InMemoryHistoryStore()
        history.append(InstanceCreated("order-7"))
        assert replay_next_occurrence(history) == 1
